"""
golden_lib.py
=============
Core utilities for aviation pipeline regression testing.

Provides functions to execute the deterministic pipeline, extract and stabilize 
outputs (including prediction probabilities), and perform invariant structural 
checks on the results. Excludes volatile file paths to ensure golden snapshots 
remain environmentally agnostic.
"""
from __future__ import annotations
import json
from pathlib import Path

# I/O path keys that add no behavioral signal (vary by workdir/machine)
EXCLUDE_KEYS = {"queue_path", "queue", "out", "model", "feats", "preds",
                "flight_dir", "metadata", "path", "hitl_summary"}
STEP_ORDER = ["inspect", "featurize", "classify", "recommend"]


def run_and_snapshot(run_pipeline, flight_dir, metadata, model, workdir, top_k=10) -> dict:
    """
    Executes the pipeline and assembles a deterministic snapshot of the output.
    
    Reads the resulting predictions from the working directory, sorts them by 
    flight identifier for order stability, and separates the raw human-in-the-loop 
    summary string for structural evaluation rather than direct string comparison.
    
    Args:
        run_pipeline (callable): The main pipeline execution function.
        flight_dir (str | Path): Directory containing flight time-series data.
        metadata (str | Path): Path to the metadata index CSV.
        model (str | Path): Path to the trained model bundle.
        workdir (str | Path): Working directory for intermediate and output files.
        top_k (int, optional): Maximum number of top anomalous flights to queue. Defaults to 10.
        
    Returns:
        dict: A snapshot dictionary containing the pipeline result, sorted 
            predictions, and the raw human-in-the-loop summary.
    """
    out = run_pipeline(flight_dir=flight_dir, metadata=metadata, model=model,
                       workdir=workdir, top_k=top_k)
    preds_path = Path(workdir) / "preds.json"
    predictions = json.loads(preds_path.read_text())["predictions"]
    # sort predictions by flight id for order-stability
    predictions = sorted(predictions, key=lambda p: str(p.get("flight", p.get("filename", ""))))
    return {"result": out, "predictions": predictions,
            "_hitl_summary_raw": out.get("hitl_summary", "")}   # kept out-of-band for structural checks


def check_invariants(snapshot: dict, top_k: int = 10) -> list[str]:
    """
    Validates structural integrity and logical invariants of the pipeline output.
    
    Ensures that the output adheres to expected formats and logical bounds, 
    identifying regressions that could theoretically be captured and frozen 
    into a broken golden snapshot.
    
    Args:
        snapshot (dict): The output snapshot generated by `run_and_snapshot`.
        top_k (int, optional): The expected maximum queue limit. Defaults to 10.
        
    Returns:
        list[str]: A list of invariant violation error messages. An empty 
            list indicates all structural checks passed.
    """
    errs = []
    out = snapshot["result"]
    trace = out.get("trace", [])
    names = [s["step"] for s in trace]
    if names != STEP_ORDER:
        errs.append(f"trace steps {names} != {STEP_ORDER}")

    res = {s["step"]: s["result"] for s in trace}
    uc = out.get("urgency_counts", {})
    n_scored = res.get("classify", {}).get("n_scored")
    if n_scored is not None and sum(uc.values()) != n_scored:
        errs.append(f"urgency_counts sum {sum(uc.values())} != n_scored {n_scored}")

    n_queued = res.get("recommend", {}).get("n_queued")
    if n_queued is not None and n_queued > top_k:
        errs.append(f"n_queued {n_queued} > top_k {top_k}")

    for p in snapshot["predictions"]:
        pm = p.get("p_maintenance", p.get("p"))
        if pm is not None and not (0.0 <= float(pm) <= 1.0):
            errs.append(f"prediction p out of [0,1]: {pm}")
            break
    urgencies = {p.get("urgency") for p in snapshot["predictions"] if "urgency" in p}
    if urgencies and not urgencies <= {"HIGH", "MEDIUM", "LOW"}:
        errs.append(f"unexpected urgency labels: {urgencies}")

    summary = snapshot.get("_hitl_summary_raw", "")
    if "HUMAN-IN-THE-LOOP" not in summary:
        errs.append("hitl_summary missing header")
    for u in ("HIGH", "MEDIUM", "LOW"):
        if f"{u}=" not in summary:
            errs.append(f"hitl_summary missing {u}= count")
    return errs
