"""
featurize_spec.py
===============================================================
Executes dynamic feature specifications against raw flight data.

This module provides the deterministic runtime needed by the automated 
discovery process. It takes a JSON feature specification (generated by 
the discovery agent) and applies the corresponding mathematical transforms 
to raw flight channels to produce a standard feature table. 
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable, Iterator

import numpy as np
import pandas as pd

try:
    from . import feature_transforms as ft
except ImportError:
    import feature_transforms as ft


@dataclass
class FlightRecord:
    filename: str
    group: str            # tail number -- the GroupKFold key
    label: int
    channels: dict[str, np.ndarray]
    fold: object = None   # paper_split fold id, carried through verbatim
    n_steps: int | None = None


FlightIter = Callable[[], Iterable[FlightRecord]]


# --------------------------------------------------------------------------
# spec validation + hashing
# --------------------------------------------------------------------------

def canonical_spec(spec: dict) -> dict:
    if "features" not in spec or not spec["features"]:
        raise ValueError("spec must contain a non-empty 'features' list")
    norm = []
    for i, entry in enumerate(spec["features"]):
        name = entry.get("transform")
        t = ft.get(name)
        channels = entry.get("channels")
        if not channels:
            raise ValueError(f"feature[{i}] ({name}) has no 'channels'")
        params = entry.get("params", {})
        unknown = set(params) - set(t.defaults)
        if unknown:
            raise ValueError(f"feature[{i}] ({name}) unknown params {unknown}; "
                             f"valid: {sorted(t.defaults)}")
        norm.append({"transform": name, "channels": list(channels),
                     "params": {**t.defaults, **params}})
    payload = json.dumps(norm, sort_keys=True)
    spec_id = spec.get("spec_id") or "spec_" + hashlib.sha1(payload.encode()).hexdigest()[:10]
    return {"spec_id": spec_id, "features": norm}


def featurize_one(record: FlightRecord, spec: dict) -> dict:
    """Apply a canonical spec to one flight -> flat feature dict."""
    row: dict[str, float] = {}
    for entry in spec["features"]:
        name, params = entry["transform"], entry["params"]
        for ch in entry["channels"]:
            if ch not in record.channels:
                continue
            feats = ft.apply(name, record.channels[ch], params)
            if name == "summary_stats":
                for k, v in feats.items():
                    row[f"{ch}__{k}"] = v          # short legacy name for parity
            else:
                for k, v in feats.items():
                    row[f"{ch}__{name}__{k}"] = v
    return row


def build_table(flight_iter: FlightIter, spec: dict, include_n_steps: bool = True,
                progress_every: int = 0) -> pd.DataFrame:
    """Execute a spec over every flight -> standard pipeline table.

    include_n_steps appends the global `__n_steps` feature that
    build_feature_table_streaming also emits (keep True for parity)."""
    spec = canonical_spec(spec)
    rows, meta = [], []
    for i, rec in enumerate(flight_iter()):
        r = featurize_one(rec, spec)
        if include_n_steps:
            r["__n_steps"] = int(rec.n_steps if rec.n_steps is not None
                                 else len(next(iter(rec.channels.values()))))
        rows.append(r)
        m = {"filename": rec.filename, "group": rec.group, "label": int(rec.label)}
        if rec.fold is not None:
            m["paper_split"] = rec.fold
        meta.append(m)
        if progress_every and (i + 1) % progress_every == 0:
            print(f"  featurized {i + 1} flights")
    if not rows:
        raise RuntimeError("flight_iter yielded no flights")
    table = pd.concat([pd.DataFrame(meta), pd.DataFrame(rows).fillna(0.0)], axis=1)
    return table


def feature_columns(table: pd.DataFrame) -> list[str]:
    reserved = {"filename", "group", "label", "paper_split"}
    return [c for c in table.columns if c not in reserved]


# --------------------------------------------------------------------------
# real-data flight iterators
# --------------------------------------------------------------------------

def realdata_flight_iter(csv_path, chunksize: int = 500_000,
                         max_flights: int | None = None) -> FlightIter:
    """Stream flights from the big per-cluster CSV via the validated
    scripts.realdata streaming loader. One pass; chunk-invariant."""
    def _iter() -> Iterator[FlightRecord]:
        try:
            from .realdata import _iter_flights, resolve_label, NGAFID_NON_SENSOR
        except ImportError:
            from scripts.realdata import _iter_flights, resolve_label, NGAFID_NON_SENSOR
        sensors = [c for c in pd.read_csv(csv_path, nrows=0).columns
                   if c not in NGAFID_NON_SENSOR]
        n = 0
        for fid, plane, raw_label, split, sens_df in _iter_flights(
                csv_path, sensors, "id", "plane_id", "before_after", "split", chunksize):
            yield FlightRecord(
                filename=str(fid),
                group=str(plane),
                label=resolve_label(raw_label),
                channels={c: sens_df[c].to_numpy() for c in sensors},
                fold=split,
                n_steps=int(len(sens_df)),
            )
            n += 1
            if max_flights and n >= max_flights:
                return
    return _iter


def collect_balanced_sample(csv_path, per_fold: int = 60, folds=("0", "1", "2", "3", "4"),
                            chunksize: int = 500_000) -> list[FlightRecord]:
    """Fold-balanced small batch for fast discovery. Streams once, keeps up to
    `per_fold` flights per fold, stops as soon as every fold is satisfied. This
    guarantees the holdout fold is populated and train/holdout both have signal,
    which a plain first-N `max_flights` cap does NOT (first-N can skew to one
    fold). Returns a materialized list -> pass `lambda: sample` as flight_iter so
    every spec evaluation reuses these in-memory arrays instead of re-streaming
    the multi-GB file."""
    folds = [str(f) for f in folds]
    want = {f: per_fold for f in folds}
    got: dict[str, int] = {f: 0 for f in folds}
    sample: list[FlightRecord] = []
    for rec in realdata_flight_iter(csv_path, chunksize)():
        f = str(rec.fold)
        if f in want and got[f] < want[f]:
            sample.append(rec)
            got[f] += 1
            if all(got[k] >= want[k] for k in folds):
                break
    print(f"[discovery] balanced sample: {len(sample)} flights | "
          f"per-fold counts {got}")
    return sample


def materialize(flight_iter: FlightIter) -> FlightIter:
    """Load raw flights once; return an iterator over the cached list."""
    cached = list(flight_iter())
    return lambda: cached


# --------------------------------------------------------------------------
# operational builders: one spec -> training table AND runtime table
# --------------------------------------------------------------------------

def build_training_table(csv_path, spec: dict, max_flights: int | None = None,
                         chunksize: int = 500_000) -> pd.DataFrame:
    """TRAIN-TIME entry point. Spec-driven replacement for
    build_feature_table_streaming: stream the big CSV, apply the frozen spec,
    return a table ready for fit_excluding_fold (carries paper_split)."""
    it = realdata_flight_iter(csv_path, chunksize, max_flights)
    return build_table(it, spec, include_n_steps=True, progress_every=500)


def build_feature_table_from_dir(flight_dir, metadata_path, spec: dict,
                                 file_col="filename", label_col="label",
                                 group_col="plane_id") -> pd.DataFrame:
    """AGENT-RUNTIME entry point. Spec-driven featurization over an exported
    flight directory (the `realdata export` output). Produces the SAME feature
    columns as build_training_table for the same spec, so classify_flights'
    reindex-to-model-columns lines up exactly."""
    flight_dir = Path(flight_dir)
    md = pd.read_csv(metadata_path)
    spec_c = canonical_spec(spec)

    def _iter():
        for _, r in md.iterrows():
            df = pd.read_csv(flight_dir / str(r[file_col]))
            yield FlightRecord(
                filename=str(r[file_col]),
                group=str(r[group_col]) if group_col in md.columns else "NA",
                label=int(r[label_col]) if label_col in md.columns else 0,
                channels={c: df[c].to_numpy() for c in df.columns},
                fold=None,
                n_steps=int(len(df)),
            )
    return build_table(_iter, spec_c, include_n_steps=True)